#!/bin/bash

cat >.git/hooks/pre-commit <<EOF
#!/bin/bash
echo Use nvm...
source ~/.nvm/nvm.sh
nvm use || exit 1

echo Install...
npm install || exit 1
echo Build...
npm run build || exit 1
echo Test...
npm test || exit 1
EOF
chmod 755 .git/hooks/pre-commit