name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install libraries
        run: cd johannes-qvarford.github.io && npm install
      - name: Build site
        run: cd johannes-qvarford.github.io && npm run build
      - name: Run tests
        run: cd johannes-qvarford.github.io && npm test
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: johannes-qvarford.github.io/out
